Controllers
umair-rao/New-Blog-App pull request #5
Opened 2024-01-18 14:49 UTC by umair-rao

In this PR I have implemented following changing, you are requested to please review.

✅ For each URL you should create:

✅A route.
✅An action in the correct controller.
✅A view file.
✅View files should include only placeholders written in plain HTML, e.g:
✅Here is a list of posts for a given user
✅Make sure that you added code to handle only the 4 required URLs.

✅When run the rails routes command in your console it shows same output as required.

2024-01-18 15:04 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @umair-rao👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with controllers. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 15:04 UTC, thecodechaser commented on config/routes.rb
> +  end
- [ ] Please make sure to only expose the index and show routes for the user and post. We should never expose routes that don't support current features.
  - You can consider using the code.
```ruby
 resources :users, only: [:show, :index] do
    resources :posts, only: [:show, :index,] do
      end
   end
```

2024-01-19 06:24 UTC, umair-rao commented on config/routes.rb
> +  end
Thank you for pointing out. I have updated the routes.

2024-01-19 06:44 UTC, shahadat3669 approved these changes
Hi @umair-rao, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ No linter Errors
✅ Worked on the Previous reviewer's comments.
✅ The code is top-notch! 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 06:44 UTC, shahadat3669 commented on config/routes.rb
> +   end
- [ ] [Optional] Great work so far on updating your code. However, there are still some changes that need to be made. In the resources :posts block, the :index action has an extra comma at the end of the only array on line number 7. While this may not cause an error in Ruby, it could be a typo or unnecessary. Additionally, since there are no routes inside the post, the do block is unnecessary. You can modify it using the following approach.
```suggestion
  resources :users, only: [:show, :index] do
    resources :posts, only: [:show, :index]
  end
```

2024-01-19 08:36 UTC, merged